### ISSUE TITLE
Your token here lol

### ISSUE THREAD

**Issue by KaffinPX** [ThuyTaiZ/horiGiveaway#2]
![image](https://user-images.githubusercontent.com/73744616/115124520-59e09500-9fcb-11eb-960f-2cbc9e556ce6.png)

**Comment by ThuyTaiZ** [comment]
Oh man.. I regenerated the token. I bet you can get in the token >:)

**Comment by KaffinPX** [comment]
lol

**Comment by gfhsbfg** [comment]
lol nice try but discord is stoping you by regen it again. Smart discord, smart.
